#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Modificado por yuriy 7.2.2020
index:
    path: /
    controller: App\Controller\IndexController::index
home:
    path: /home
    controller: App\Controller\HomeController::index
app_logout:
    path: /logout
    methods: GET
