#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Modificado por yuriy 6.2.2020
home:
    path: /home
    controller: App\Controller\HomeController::index
app_logout:
    path: /logout
    methods: GET