#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Modificado por yuriy 7.2.2020
index:
    path: /
    controller: App\Controller\IndexController::index
home:
    path: /home
    controller: App\Controller\HomeController::index
usuarios:
    path: /usuarios
    controller: App\Controller\UsuariosController::index
ciudades:
    path: /ciudades
    controller: App\Controller\CiudadesController::index
#borrar_foto:
#    path:       /usuarios/borrar/{imagen}
#    controller: App\Controller\UsuariosController::borrarFoto
aficiones:
    path: /aficiones
    controller: App\Controller\AficionesController::index
app_logout:
    path: /logout
    methods: GET
