<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP4ks9Cf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP4ks9Cf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP4ks9Cf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP4ks9Cf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP4ks9Cf\App_KernelDevDebugContainer([
    'container.build_hash' => 'P4ks9Cf',
    'container.build_id' => 'aa49eb0c',
    'container.build_time' => 1580915052,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP4ks9Cf');
